#define VISITED -1
#define EMPTY 0
#define SUB 1
#define HOSTILE 2
#define SURVIVOR 3
#define SUB_START_X 0
#define SUB_START_Y 0
#define BOARD_H 5
#define BOARD_W 10
#define SUB_CAP 1
#define SURVIVOR_COUNT 3
#define HOSTILE_COUNT 3